version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: real_estate_api
    working_dir: /app-backend
    volumes:
      - ./src:/app-backend/src
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0.29
    container_name: real_estate_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    ports:
      - '33060:3306'
    volumes:
      - ./real_estate.sql:/docker-entrypoint-initdb.d/tarefas_script.sql
